//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppBaev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationSystemKyrsachEntities : DbContext
    {
        private static EducationSystemKyrsachEntities _context;
        public EducationSystemKyrsachEntities()
            : base("name=EducationSystemKyrsachEntities")
        {
        }
        public static EducationSystemKyrsachEntities GetContext()
        {
            if (_context == null)
            {
                _context = new EducationSystemKyrsachEntities();

            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<EducationPrograms> EducationPrograms { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<TestResults> TestResults { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
