//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppBaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int MaterialID { get; set; }
        public int CourseID { get; set; }
        public string MaterialType { get; set; }
        public string MaterialLink { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
