//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppBaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public int ResultID { get; set; }
        public int UserID { get; set; }
        public int TestID { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> Passed { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
    }
}
